### ISSUE TITLE
Add seller social info section 

### ISSUE THREAD

**Issue by restrading** [councilofelders/numerbay#16]
This is a feature request from the CoE spaces: allow sellers to display their socials (e.g. rocketchat link) so that buyers and others can contact them.

**Comment by aqsmith08** [comment]
Hi restrading,

I'd like to +1 this feature. My user story is:

- As a NumerBay buyer, I'd like to contact NumerBay sellers so that I can purchase models that they submit to Numerai or Signals which are not currently available for purchase on NumerBay.

I know that email address is an account attribute that already exists on NumerBay, but I'm totally okay to use Rocketchat, social media as well. Thanks so much for all your work on NumerBay! :+1:
